[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "weiss-api"
version = "2.0.0"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
description = "WEISS' backend (API)"

dependencies = [
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "cryptography>=50.0.1",
    "msal>=1.38.0",
    "uvicorn[standard]>=0.52.4",
    "python-multipart>=0.0.32",
    "authlib>=1.8.0",
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "ruff"
]

[project.urls]
GitHub = "https://github.com/weiss-controls/weiss"

[[project.authors]]
name = "André Favoto"
email = "andrefavotto@hotmail.com"

[[project.authors]]
email = "guilherme.de-freitas@diamond.ac.uk"
name = "Guilherme de Freitas"

[tool.ruff]
src = ["src", "tests"]
line-length = 120
lint.select = [
    "C4",   # flake8-comprehensions - https://beta.ruff.rs/docs/rules/#flake8-comprehensions-c4
    "E",    # pycodestyle errors - https://beta.ruff.rs/docs/rules/#error-e
    "F",    # pyflakes rules - https://beta.ruff.rs/docs/rules/#pyflakes-f
    "W",    # pycodestyle warnings - https://beta.ruff.rs/docs/rules/#warning-w
    "I001", # isort
]

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]
