services:
  weiss-dev:
    build:
      context: "."
      target: dev
    volumes:
      - .:/app # Mount the source code for development
      - /app/node_modules # Prevent host node_modules from interfering
    image: weiss-dev:${DOCKER_TAG:-latest}
    container_name: weiss-dev
    network_mode: host
    restart: always
    environment:
      NODE_ENV: development
      VITE_DEMO_MODE: ${VITE_DEMO_MODE:-false}
    depends_on:
      - weiss-epicsws-dev
      - weiss-api-dev
  weiss-epicsws-dev:
    build:
      context: ./backend/epicsWS
    volumes:
      - ./backend/epicsWS:/app
    image: weiss-epicsws-dev:${DOCKER_TAG:-latest}
    container_name: weiss-epicsws-dev
    network_mode: host
    restart: always
    environment:
      EPICS_DEFAULT_PROTOCOL: ${EPICS_DEFAULT_PROTOCOL}
      EPICS_CA_ADDR_LIST: ${EPICS_CA_ADDR_LIST}
      EPICS_CA_AUTO_ADDR_LIST: ${EPICS_CA_AUTO_ADDR_LIST}
      EPICS_CA_MAX_ARRAY_BYTES: ${EPICS_CA_MAX_ARRAY_BYTES}
      EPICS_PVA_ADDR_LIST: ${EPICS_PVA_ADDR_LIST}
      EPICS_PVA_AUTO_ADDR_LIST: ${EPICS_PVA_AUTO_ADDR_LIST}

  weiss-api-dev:
    build:
      context: ./backend/api
    volumes:
      - ./backend/api:/app/api
      - storage:/app/storage
      - ${ROLES_CONFIG_FILE:-./backend/roles.example.toml}:/config/roles.toml:ro
    image: weiss-api-dev:${DOCKER_TAG:-latest}
    container_name: weiss-api-dev
    ports:
      - "8000:8000"
    restart: always
    environment:
      DEV_MODE: true # used to derive FRONTEND_URL port for CORS dev setup
      MS_AUTH_CLIENT_ID: ${MS_AUTH_CLIENT_ID}
      MS_AUTH_TENANT_ID: ${MS_AUTH_TENANT_ID}
      MS_AUTH_CLIENT_SECRET: ${MS_AUTH_CLIENT_SECRET}
      APP_HOSTNAME: ${APP_HOSTNAME:-localhost}
      ENABLE_HTTPS: ${ENABLE_HTTPS:-false}
      TECHNICAL_ACCOUNT_TOKEN: ${TECHNICAL_ACCOUNT_TOKEN}
      TECHNICAL_ACCOUNT_USERNAME: ${TECHNICAL_ACCOUNT_USERNAME}
      TECHNICAL_ACCOUNT_EMAIL: ${TECHNICAL_ACCOUNT_EMAIL}
      ROLES_CONFIG_PATH: /config/roles.toml

volumes:
  storage:
