services:
  weiss-dev:
    build:
      context: "."
      target: dev
    volumes:
      - .:/app # Mount the source code for development
      - /app/node_modules # Prevent host node_modules from interfering
    image: weiss-dev:${DOCKER_TAG:-latest}
    container_name: weiss-dev
    network_mode: host
    tty: true
    restart: always
    environment:
      NODE_ENV: development
      VITE_DEMO_MODE: ${DEMO_MODE:-false}
      VITE_AUTH_IDENTITY_PROVIDER: ${AUTH_IDENTITY_PROVIDER:-oauth}
    depends_on:
      - weiss-epicsws-dev
      - weiss-api-dev
  weiss-epicsws-dev:
    build:
      context: ./backend/epicsWS
    volumes:
      - ./backend/epicsWS:/app
    image: weiss-epicsws-dev:${DOCKER_TAG:-latest}
    container_name: weiss-epicsws-dev
    network_mode: host
    restart: always
    environment:
      EPICS_DEFAULT_PROTOCOL: ${EPICS_DEFAULT_PROTOCOL}
      EPICS_CA_ADDR_LIST: ${EPICS_CA_ADDR_LIST}
      EPICS_CA_AUTO_ADDR_LIST: ${EPICS_CA_AUTO_ADDR_LIST}
      EPICS_CA_MAX_ARRAY_BYTES: ${EPICS_CA_MAX_ARRAY_BYTES}
      EPICS_PVA_ADDR_LIST: ${EPICS_PVA_ADDR_LIST}
      EPICS_PVA_AUTO_ADDR_LIST: ${EPICS_PVA_AUTO_ADDR_LIST}
      EPICS_MAX_UPDATE_RATE_HZ: ${EPICS_MAX_UPDATE_RATE_HZ}

  weiss-api-dev:
    build:
      context: ./backend/api
    working_dir: /app/api
    # override to allow hot-reloading of FastAPI
    command: api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/api:/app/api
      - storage:/app/storage
      - ${ROLES_CONFIG_FILE:-./backend/api/roles.example.toml}:/config/roles.toml:ro
    image: weiss-api-dev:${DOCKER_TAG:-latest}
    container_name: weiss-api-dev
    ports:
      - "8000:8000"
    restart: always
    environment:
      DEV_MODE: true # used to derive FRONTEND_URL port for CORS dev setup
      PYTHONPATH: /app/api/src
      DEMO_MODE: ${DEMO_MODE:-true}
      AUTH_CLIENT_ID: ${AUTH_CLIENT_ID}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
      AUTH_IDENTITY_PROVIDER: ${AUTH_IDENTITY_PROVIDER:-oauth}
      AUTH_ISSUER: ${AUTH_ISSUER}
      APP_HOSTNAME: ${APP_HOSTNAME:-localhost}
      ENABLE_HTTPS: ${ENABLE_HTTPS:-false}
      TECHNICAL_ACCOUNT_TOKEN: ${TECHNICAL_ACCOUNT_TOKEN}
      TECHNICAL_ACCOUNT_USERNAME: ${TECHNICAL_ACCOUNT_USERNAME}
      TECHNICAL_ACCOUNT_EMAIL: ${TECHNICAL_ACCOUNT_EMAIL}
      ROLES_CONFIG_PATH: /config/roles.toml

volumes:
  storage:
