[project]
name = "weiss-epicsws"
version = "2.0.0"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]
description = "WEISS EPICS WebSocket bridge"
requires-python = ">=3.12"
dependencies = [
    "p4p==4.3.0",
    "pyepics==3.5.10",
    "websockets==17.1",
]

[project.urls]
GitHub = "https://github.com/weiss-controls/weiss"

[tool.ruff]
src = ["."]
line-length = 120

lint.select = [
    "C4",   # flake8-comprehensions
    "E",    # pycodestyle errors
    "F",    # pyflakes rules
    "W",    # pycodestyle warnings
    "I001", # isort
]

[dependency-groups]
dev = [
    "ruff>=0.16.6",
]
