// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AuthCallbackData,
  AuthCallbackErrors,
  AuthCallbackResponses,
  AuthGetAuthUrlData,
  AuthGetAuthUrlErrors,
  AuthGetAuthUrlResponses,
  AuthLogoutData,
  AuthLogoutResponses,
  AuthMeData,
  AuthMeResponses,
  AuthReloadRolesData,
  AuthReloadRolesResponses,
  CheckoutRepoRefData,
  CheckoutRepoRefErrors,
  CheckoutRepoRefResponses,
  CommitStagingRepoData,
  CommitStagingRepoErrors,
  CommitStagingRepoResponses,
  CreateStagingRepoPathData,
  CreateStagingRepoPathErrors,
  CreateStagingRepoPathResponses,
  DeleteSnapshotData,
  DeleteSnapshotErrors,
  DeleteSnapshotResponses,
  DeleteStagingRepoPathData,
  DeleteStagingRepoPathErrors,
  DeleteStagingRepoPathResponses,
  DeployRepoData,
  DeployRepoErrors,
  DeployRepoResponses,
  GetAllDeployedReposTreeData,
  GetAllDeployedReposTreeResponses,
  GetAllReposTreeData,
  GetAllReposTreeResponses,
  GetDeployedRepoFileData,
  GetDeployedRepoFileErrors,
  GetDeployedRepoFileResponses,
  GetDeployedRepoTreeData,
  GetDeployedRepoTreeErrors,
  GetDeployedRepoTreeResponses,
  GetSnapshotData,
  GetSnapshotErrors,
  GetSnapshotResponses,
  GetStagingRepoFileData,
  GetStagingRepoFileErrors,
  GetStagingRepoFileResponses,
  GetStagingRepoTreeData,
  GetStagingRepoTreeErrors,
  GetStagingRepoTreeResponses,
  GetTokenStatusData,
  GetTokenStatusResponses,
  HealthCheckData,
  HealthCheckResponses,
  ListDeployedReposData,
  ListDeployedReposResponses,
  ListRepoRefsData,
  ListRepoRefsErrors,
  ListRepoRefsResponses,
  ListReposData,
  ListReposResponses,
  ListSnapshotsData,
  ListSnapshotsErrors,
  ListSnapshotsResponses,
  MoveStagingRepoPathData,
  MoveStagingRepoPathErrors,
  MoveStagingRepoPathResponses,
  RegisterRepoData,
  RegisterRepoErrors,
  RegisterRepoResponses,
  RenameStagingRepoPathData,
  RenameStagingRepoPathErrors,
  RenameStagingRepoPathResponses,
  ResetStagingRepoData,
  ResetStagingRepoErrors,
  ResetStagingRepoFileData,
  ResetStagingRepoFileErrors,
  ResetStagingRepoFileResponses,
  ResetStagingRepoPathData,
  ResetStagingRepoPathErrors,
  ResetStagingRepoPathResponses,
  ResetStagingRepoResponses,
  RootInfoData,
  RootInfoResponses,
  SaveSnapshotData,
  SaveSnapshotErrors,
  SaveSnapshotResponses,
  SyncRepoData,
  SyncRepoErrors,
  SyncRepoResponses,
  UndeployRepoData,
  UndeployRepoErrors,
  UndeployRepoResponses,
  UnregisterRepoData,
  UnregisterRepoErrors,
  UnregisterRepoResponses,
  UpdateStagingRepoFileData,
  UpdateStagingRepoFileErrors,
  UpdateStagingRepoFileResponses,
  UploadStagingRepoFileData,
  UploadStagingRepoFileErrors,
  UploadStagingRepoFileResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Authorize
 */
export const authGetAuthUrl = <ThrowOnError extends boolean = true>(
  options: Options<AuthGetAuthUrlData, ThrowOnError>,
) =>
  (options.client ?? client).get<AuthGetAuthUrlResponses, AuthGetAuthUrlErrors, ThrowOnError>({
    url: "/api/v1/auth/{provider}/authorize",
    ...options,
  });

/**
 * Oauth Callback
 */
export const authCallback = <ThrowOnError extends boolean = true>(
  options: Options<AuthCallbackData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthCallbackResponses, AuthCallbackErrors, ThrowOnError>({
    url: "/api/v1/auth/callback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Me
 */
export const authMe = <ThrowOnError extends boolean = true>(
  options?: Options<AuthMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuthMeResponses, unknown, ThrowOnError>({
    url: "/api/v1/auth/me",
    ...options,
  });

/**
 * Logout
 */
export const authLogout = <ThrowOnError extends boolean = true>(
  options?: Options<AuthLogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({
    url: "/api/v1/auth/logout",
    ...options,
  });

/**
 * Reload Roles
 */
export const authReloadRoles = <ThrowOnError extends boolean = true>(
  options?: Options<AuthReloadRolesData, ThrowOnError>,
) =>
  (options?.client ?? client).post<AuthReloadRolesResponses, unknown, ThrowOnError>({
    url: "/api/v1/auth/admin/reload-roles",
    ...options,
  });

/**
 * Get Token Status
 *
 * Return whether the configured PAT technical-account token is able to
 * authenticate against the remote hosting platform's API.
 */
export const getTokenStatus = <ThrowOnError extends boolean = true>(
  options?: Options<GetTokenStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetTokenStatusResponses, unknown, ThrowOnError>({
    url: "/api/v1/repos/staging/token-status",
    ...options,
  });

/**
 * List Repositories
 */
export const listRepos = <ThrowOnError extends boolean = true>(
  options?: Options<ListReposData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListReposResponses, unknown, ThrowOnError>({
    url: "/api/v1/repos/staging/",
    ...options,
  });

/**
 * Get All Repos Tree
 */
export const getAllReposTree = <ThrowOnError extends boolean = true>(
  options?: Options<GetAllReposTreeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetAllReposTreeResponses, unknown, ThrowOnError>({
    url: "/api/v1/repos/staging/tree",
    ...options,
  });

/**
 * Register Repository
 *
 * Register a Git repository and create a clone
 */
export const registerRepo = <ThrowOnError extends boolean = true>(
  options: Options<RegisterRepoData, ThrowOnError>,
) =>
  (options.client ?? client).post<RegisterRepoResponses, RegisterRepoErrors, ThrowOnError>({
    url: "/api/v1/repos/staging/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Unregister Repository
 *
 * Remove a repository completely:
 * - Delete staging folder
 * - Delete all deployments
 * - Remove repo metadata
 */
export const unregisterRepo = <ThrowOnError extends boolean = true>(
  options: Options<UnregisterRepoData, ThrowOnError>,
) =>
  (options.client ?? client).delete<UnregisterRepoResponses, UnregisterRepoErrors, ThrowOnError>({
    url: "/api/v1/repos/staging/{repo_id}/unregister",
    ...options,
  });

/**
 * List Repository Refs
 *
 * List 20 latest repository refs available. Assumes repo is up to date.
 * If commit is tagged, show tag instead of SHA.
 */
export const listRepoRefs = <ThrowOnError extends boolean = true>(
  options: Options<ListRepoRefsData, ThrowOnError>,
) =>
  (options.client ?? client).get<ListRepoRefsResponses, ListRepoRefsErrors, ThrowOnError>({
    url: "/api/v1/repos/staging/{repo_id}/refs",
    ...options,
  });

/**
 * Update Repo
 *
 * Fetch new tags/commits from default branch and rebase current worktree onto it.
 * This is done so we keep commit history always linear.
 * If the rebase or fetch fails, the user's changes are restored unchanged and an error is returned.
 */
export const syncRepo = <ThrowOnError extends boolean = true>(
  options: Options<SyncRepoData, ThrowOnError>,
) =>
  (options.client ?? client).post<SyncRepoResponses, SyncRepoErrors, ThrowOnError>({
    url: "/api/v1/repos/staging/{repo_id}/sync",
    ...options,
  });

/**
 * Staging Get Repo File
 *
 * Return the content of a file from the current state of staging repo.
 */
export const getStagingRepoFile = <ThrowOnError extends boolean = true>(
  options: Options<GetStagingRepoFileData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStagingRepoFileResponses,
    GetStagingRepoFileErrors,
    ThrowOnError
  >({ url: "/api/v1/repos/staging/{repo_id}/file", ...options });

/**
 * Staging Update Repo File
 *
 * Overwrite the contents of an existing file in the staging repository.
 * Path must always be relative to repo root.
 * Fails if the file does not already exist.
 */
export const updateStagingRepoFile = <ThrowOnError extends boolean = true>(
  options: Options<UpdateStagingRepoFileData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateStagingRepoFileResponses,
    UpdateStagingRepoFileErrors,
    ThrowOnError
  >({
    url: "/api/v1/repos/staging/{repo_id}/file",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Upload Staging Repo File
 *
 * Upload a file to the staging repository.
 * Creates or overwrites the file at the given path.
 * Intermediate directories are created as needed.
 */
export const uploadStagingRepoFile = <ThrowOnError extends boolean = true>(
  options: Options<UploadStagingRepoFileData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    UploadStagingRepoFileResponses,
    UploadStagingRepoFileErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/api/v1/repos/staging/{repo_id}/upload",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Reset Staging Repo File
 *
 * Reset changes of a single file in the staging repository.
 *
 * .. deprecated::
 * Use ``POST /{repo_id}/path/reset`` instead, which handles both files and directories.
 *
 * @deprecated
 */
export const resetStagingRepoFile = <ThrowOnError extends boolean = true>(
  options: Options<ResetStagingRepoFileData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResetStagingRepoFileResponses,
    ResetStagingRepoFileErrors,
    ThrowOnError
  >({ url: "/api/v1/repos/staging/{repo_id}/file/reset", ...options });

/**
 * Reset Staging Repo Path
 *
 * Revert uncommitted changes for a single file or directory in the staging repository.
 *
 * For tracked files/directories: restores them to the last committed state.
 * For newly added (untracked) files/directories: removes them entirely.
 */
export const resetStagingRepoPath = <ThrowOnError extends boolean = true>(
  options: Options<ResetStagingRepoPathData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    ResetStagingRepoPathResponses,
    ResetStagingRepoPathErrors,
    ThrowOnError
  >({ url: "/api/v1/repos/staging/{repo_id}/path/reset", ...options });

/**
 * Reset Staging Repo
 *
 * Return the staging repository to the checked-out ref.
 * This discards all local changes, including untracked files and directories.
 */
export const resetStagingRepo = <ThrowOnError extends boolean = true>(
  options: Options<ResetStagingRepoData, ThrowOnError>,
) =>
  (options.client ?? client).post<ResetStagingRepoResponses, ResetStagingRepoErrors, ThrowOnError>({
    url: "/api/v1/repos/staging/{repo_id}/reset",
    ...options,
  });

/**
 * Delete Staging Repo Path
 *
 * Delete a file or directory from the staging repository.
 * Directories are deleted recursively.
 */
export const deleteStagingRepoPath = <ThrowOnError extends boolean = true>(
  options: Options<DeleteStagingRepoPathData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteStagingRepoPathResponses,
    DeleteStagingRepoPathErrors,
    ThrowOnError
  >({ url: "/api/v1/repos/staging/{repo_id}/path", ...options });

/**
 * Create Staging Repo Path
 *
 * Create a file or directory in the staging repository.
 * - Intermediate directories will be created if necessary.
 * - Directories get a .gitkeep file to ensure they are tracked by Git.
 */
export const createStagingRepoPath = <ThrowOnError extends boolean = true>(
  options: Options<CreateStagingRepoPathData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateStagingRepoPathResponses,
    CreateStagingRepoPathErrors,
    ThrowOnError
  >({
    url: "/api/v1/repos/staging/{repo_id}/path",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Rename Staging Repo Path
 *
 * Rename a file or directory in the staging repository.
 */
export const renameStagingRepoPath = <ThrowOnError extends boolean = true>(
  options: Options<RenameStagingRepoPathData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RenameStagingRepoPathResponses,
    RenameStagingRepoPathErrors,
    ThrowOnError
  >({
    url: "/api/v1/repos/staging/{repo_id}/path/rename",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Move Staging Repo Path
 *
 * Move a file or directory to a different directory in the staging repository.
 * The item keeps its name; only its parent directory changes.
 * The destination must be an existing directory.
 */
export const moveStagingRepoPath = <ThrowOnError extends boolean = true>(
  options: Options<MoveStagingRepoPathData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MoveStagingRepoPathResponses,
    MoveStagingRepoPathErrors,
    ThrowOnError
  >({
    url: "/api/v1/repos/staging/{repo_id}/path/move",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Commit Staging Repo
 *
 * Commit staged changes in the staging repository and push to remote.
 * If HEAD is behind remote, try rebasing first.
 * Fails if there is nothing to commit.
 */
export const commitStagingRepo = <ThrowOnError extends boolean = true>(
  options: Options<CommitStagingRepoData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CommitStagingRepoResponses,
    CommitStagingRepoErrors,
    ThrowOnError
  >({
    url: "/api/v1/repos/staging/{repo_id}/commit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Deploy Repo
 *
 * Deploy a selected tag or commit to make it available for users
 */
export const deployRepo = <ThrowOnError extends boolean = true>(
  options: Options<DeployRepoData, ThrowOnError>,
) =>
  (options.client ?? client).post<DeployRepoResponses, DeployRepoErrors, ThrowOnError>({
    url: "/api/v1/repos/staging/{repo_id}/deploy",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Undeploy Repository
 *
 * Remove the current deployment for a repository:
 * - Delete symlink to current deployment
 * - Clear current deployment metadata in repo info
 */
export const undeployRepo = <ThrowOnError extends boolean = true>(
  options: Options<UndeployRepoData, ThrowOnError>,
) =>
  (options.client ?? client).post<UndeployRepoResponses, UndeployRepoErrors, ThrowOnError>({
    url: "/api/v1/repos/staging/{repo_id}/undeploy",
    ...options,
  });

/**
 * Checkout Repo Ref
 *
 * Checkout a specific ref in the staging repo
 */
export const checkoutRepoRef = <ThrowOnError extends boolean = true>(
  options: Options<CheckoutRepoRefData, ThrowOnError>,
) =>
  (options.client ?? client).post<CheckoutRepoRefResponses, CheckoutRepoRefErrors, ThrowOnError>({
    url: "/api/v1/repos/staging/{repo_id}/checkout",
    ...options,
  });

/**
 * Get Staging Repo Tree
 */
export const getStagingRepoTree = <ThrowOnError extends boolean = true>(
  options: Options<GetStagingRepoTreeData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetStagingRepoTreeResponses,
    GetStagingRepoTreeErrors,
    ThrowOnError
  >({ url: "/api/v1/repos/staging/{repo_id}/tree", ...options });

/**
 * List Repositories
 */
export const listDeployedRepos = <ThrowOnError extends boolean = true>(
  options?: Options<ListDeployedReposData, ThrowOnError>,
) =>
  (options?.client ?? client).get<ListDeployedReposResponses, unknown, ThrowOnError>({
    url: "/api/v1/repos/runtime/",
    ...options,
  });

/**
 * Get All Repos Tree
 */
export const getAllDeployedReposTree = <ThrowOnError extends boolean = true>(
  options?: Options<GetAllDeployedReposTreeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetAllDeployedReposTreeResponses, unknown, ThrowOnError>({
    url: "/api/v1/repos/runtime/tree",
    ...options,
  });

/**
 * Get Deployed Repo Tree
 *
 * Return the full tree of the currently deployed snapshot
 * for a single repository, wrapped in DeploymentTreeInfo.
 */
export const getDeployedRepoTree = <ThrowOnError extends boolean = true>(
  options: Options<GetDeployedRepoTreeData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDeployedRepoTreeResponses,
    GetDeployedRepoTreeErrors,
    ThrowOnError
  >({ url: "/api/v1/repos/runtime/{repo_id}/tree", ...options });

/**
 * Runtime Get Repo File
 *
 * Return the content of a file from the currently deployed snapshot.
 */
export const getDeployedRepoFile = <ThrowOnError extends boolean = true>(
  options: Options<GetDeployedRepoFileData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetDeployedRepoFileResponses,
    GetDeployedRepoFileErrors,
    ThrowOnError
  >({ url: "/api/v1/repos/runtime/{repo_id}/file", ...options });

/**
 * List all snapshots for an OPI file
 *
 * List all saved snapshots for a given OPI file.
 */
export const listSnapshots = <ThrowOnError extends boolean = true>(
  options: Options<ListSnapshotsData, ThrowOnError>,
) =>
  (options.client ?? client).get<ListSnapshotsResponses, ListSnapshotsErrors, ThrowOnError>({
    url: "/api/v1/snapshots",
    ...options,
  });

/**
 * Save a PV snapshot
 *
 * Save current PV values as a named snapshot for an OPI file.
 */
export const saveSnapshot = <ThrowOnError extends boolean = true>(
  options: Options<SaveSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).put<SaveSnapshotResponses, SaveSnapshotErrors, ThrowOnError>({
    url: "/api/v1/snapshots",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete a snapshot
 *
 * Delete a saved snapshot.
 */
export const deleteSnapshot = <ThrowOnError extends boolean = true>(
  options: Options<DeleteSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).delete<DeleteSnapshotResponses, DeleteSnapshotErrors, ThrowOnError>({
    url: "/api/v1/snapshots/{snapshot_id}",
    ...options,
  });

/**
 * Get a snapshot with all PV values
 *
 * Get full snapshot data including all PV values.
 */
export const getSnapshot = <ThrowOnError extends boolean = true>(
  options: Options<GetSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetSnapshotResponses, GetSnapshotErrors, ThrowOnError>({
    url: "/api/v1/snapshots/{snapshot_id}",
    ...options,
  });

/**
 * Root
 */
export const rootInfo = <ThrowOnError extends boolean = true>(
  options?: Options<RootInfoData, ThrowOnError>,
) =>
  (options?.client ?? client).get<RootInfoResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });

/**
 * Health
 */
export const healthCheck = <ThrowOnError extends boolean = true>(
  options?: Options<HealthCheckData, ThrowOnError>,
) =>
  (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({
    url: "/health",
    ...options,
  });
