// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * AuthProvider
 */
export type AuthProvider = "microsoft" | "demo";

/**
 * AuthURL
 */
export type AuthUrl = {
  /**
   * Authorize Url
   */
  authorize_url: string;
};

/**
 * Body_uploadStagingRepoFile
 */
export type BodyUploadStagingRepoFile = {
  /**
   * File
   */
  file: Blob | File;
};

/**
 * CommitRequest
 */
export type CommitRequest = {
  /**
   * Message
   *
   * Git commit message
   */
  message: string;
  /**
   * Tag
   *
   * Optional Git tag to add after commit
   */
  tag?: string | null;
};

/**
 * DeployRequest
 */
export type DeployRequest = {
  /**
   * Deployment Version
   */
  deployment_version: string;
};

/**
 * DeploymentMeta
 */
export type DeploymentMeta = {
  /**
   * Id
   */
  id: string;
  /**
   * Alias
   */
  alias: string;
  /**
   * Git Url
   */
  git_url: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Current Deployment
   */
  current_deployment: string;
  /**
   * Deployed Ref
   */
  deployed_ref: string;
  /**
   * Deployed At
   */
  deployed_at: string;
};

/**
 * DeploymentTreeInfo
 */
export type DeploymentTreeInfo = {
  /**
   * Id
   */
  id: string;
  /**
   * Alias
   */
  alias: string;
  /**
   * Git Url
   */
  git_url: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Current Deployment
   */
  current_deployment: string;
  /**
   * Deployed Ref
   */
  deployed_ref: string;
  /**
   * Deployed At
   */
  deployed_at: string;
  /**
   * Tree
   */
  tree: Array<TreeNode>;
};

/**
 * FileResponse
 */
export type FileResponse = {
  /**
   * Path
   */
  path: string;
  /**
   * Content
   */
  content: string;
  /**
   * Encoding
   */
  encoding?: string;
};

/**
 * FileUpdateRequest
 */
export type FileUpdateRequest = {
  /**
   * Content
   *
   * Full file content to write
   */
  content: string;
};

/**
 * GitFileStatus
 */
export type GitFileStatus = {
  /**
   * Path
   */
  path: string;
  /**
   * Status
   */
  status: "modified" | "added" | "deleted" | "renamed" | "untracked";
};

/**
 * GitWorkingTreeStatus
 */
export type GitWorkingTreeStatus = {
  /**
   * Dirty
   */
  dirty: boolean;
  /**
   * Files
   */
  files: Array<GitFileStatus>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
  /**
   * Status
   */
  status: string;
};

/**
 * OAuthCallbackRequest
 */
export type OAuthCallbackRequest = {
  provider: AuthProvider;
  /**
   * Code
   */
  code?: string | null;
  /**
   * Redirect Uri
   */
  redirect_uri?: string | null;
};

/**
 * PathCreateRequest
 */
export type PathCreateRequest = {
  /**
   * Path
   *
   * Path to create, relative to repo root
   */
  path: string;
  /**
   * Type
   *
   * Type of path to create: 'file' or 'directory'.
   */
  type: string;
};

/**
 * PathMoveRequest
 */
export type PathMoveRequest = {
  /**
   * Destination
   *
   * Destination directory path, relative to repo root. The item is moved into this directory.
   */
  destination: string;
};

/**
 * PathRenameRequest
 */
export type PathRenameRequest = {
  /**
   * New Name
   *
   * New name for the file or directory (just the name segment, not the full path)
   */
  new_name: string;
};

/**
 * ReloadRolesResponse
 */
export type ReloadRolesResponse = {
  /**
   * Reloaded
   */
  reloaded: boolean;
  /**
   * Developer Count
   */
  developer_count: number;
};

/**
 * RepoCreateRequest
 */
export type RepoCreateRequest = {
  /**
   * Alias
   *
   * Local OPI repository name
   */
  alias: string;
  /**
   * Git Url
   *
   * Git repository URL
   */
  git_url: string;
};

/**
 * RepoRef
 */
export type RepoRef = {
  /**
   * Ref
   */
  ref: string;
  /**
   * Message
   */
  message: string;
};

/**
 * RootInfo
 */
export type RootInfo = {
  /**
   * Service
   */
  service: string;
  /**
   * Version
   */
  version: string;
};

/**
 * SnapshotDetail
 */
export type SnapshotDetail = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Opi File
   */
  opi_file: string;
  /**
   * Timestamp
   */
  timestamp: string;
  /**
   * Pv Count
   */
  pv_count: number;
  /**
   * Pvs
   */
  pvs: {
    [key: string]: SnapshotPvData;
  };
};

/**
 * SnapshotEntry
 */
export type SnapshotEntry = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Opi File
   */
  opi_file: string;
  /**
   * Timestamp
   */
  timestamp: string;
  /**
   * Pv Count
   */
  pv_count: number;
};

/**
 * SnapshotPVData
 */
export type SnapshotPvData = {
  /**
   * Value
   */
  value: unknown;
  /**
   * Alarm
   */
  alarm?: {
    [key: string]: unknown;
  } | null;
  /**
   * Timestamp
   */
  timeStamp?: {
    [key: string]: unknown;
  } | null;
  /**
   * B64Arr
   */
  b64arr?: string | null;
  /**
   * B64Dtype
   */
  b64dtype?: string | null;
};

/**
 * SnapshotSaveRequest
 */
export type SnapshotSaveRequest = {
  /**
   * Name
   *
   * Snapshot name
   */
  name: string;
  /**
   * Opi File
   *
   * OPI file path this snapshot belongs to
   */
  opi_file: string;
  /**
   * Pvs
   *
   * PV name to value mapping
   */
  pvs: {
    [key: string]: SnapshotPvData;
  };
};

/**
 * StagingMeta
 */
export type StagingMeta = {
  /**
   * Id
   */
  id: string;
  /**
   * Alias
   */
  alias: string;
  /**
   * Git Url
   */
  git_url: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Current Deployment
   */
  current_deployment?: string | null;
  /**
   * Deployed Ref
   */
  deployed_ref?: string | null;
  /**
   * Deployed At
   */
  deployed_at?: string | null;
};

/**
 * StagingTreeInfo
 */
export type StagingTreeInfo = {
  /**
   * Id
   */
  id: string;
  /**
   * Alias
   */
  alias: string;
  /**
   * Git Url
   */
  git_url: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Current Deployment
   */
  current_deployment?: string | null;
  /**
   * Deployed Ref
   */
  deployed_ref?: string | null;
  /**
   * Deployed At
   */
  deployed_at?: string | null;
  /**
   * Refs
   */
  refs: Array<RepoRef>;
  /**
   * Checked Out Ref
   */
  checked_out_ref: string;
  /**
   * Tree
   */
  tree: Array<TreeNode>;
  working_tree_status: GitWorkingTreeStatus;
};

/**
 * TokenStatus
 */
export type TokenStatus = {
  /**
   * Configured
   */
  configured: boolean;
  /**
   * Valid
   */
  valid: boolean;
  /**
   * Detail
   */
  detail: string;
};

/**
 * TreeNode
 */
export type TreeNode = {
  /**
   * Name
   */
  name: string;
  /**
   * Path
   */
  path: string;
  /**
   * Type
   */
  type: "file" | "directory";
  /**
   * Children
   */
  children?: Array<TreeNode> | null;
};

/**
 * User
 */
export type User = {
  /**
   * Id
   */
  id: string;
  /**
   * Username
   */
  username: string;
  /**
   * Displayname
   */
  displayName: string;
  /**
   * Email
   */
  email: string | null;
  provider: AuthProvider;
  /**
   * Provider Id
   */
  provider_id: string;
  role?: UserRole;
  /**
   * Created At
   */
  created_at?: string;
};

/**
 * UserRole
 */
export type UserRole = "developer" | "operator";

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type AuthGetAuthUrlData = {
  body?: never;
  path: {
    provider: AuthProvider;
  };
  query?: {
    /**
     * Demo Profile
     */
    demo_profile?: UserRole | null;
  };
  url: "/api/v1/auth/{provider}/authorize";
};

export type AuthGetAuthUrlErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthGetAuthUrlError = AuthGetAuthUrlErrors[keyof AuthGetAuthUrlErrors];

export type AuthGetAuthUrlResponses = {
  /**
   * Successful Response
   */
  200: AuthUrl;
};

export type AuthGetAuthUrlResponse = AuthGetAuthUrlResponses[keyof AuthGetAuthUrlResponses];

export type AuthCallbackData = {
  body: OAuthCallbackRequest;
  path?: never;
  query?: never;
  url: "/api/v1/auth/callback";
};

export type AuthCallbackErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AuthCallbackError = AuthCallbackErrors[keyof AuthCallbackErrors];

export type AuthCallbackResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type AuthCallbackResponse = AuthCallbackResponses[keyof AuthCallbackResponses];

export type AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/me";
};

export type AuthMeResponses = {
  /**
   * Successful Response
   */
  200: User;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/logout";
};

export type AuthLogoutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthReloadRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/auth/admin/reload-roles";
};

export type AuthReloadRolesResponses = {
  /**
   * Successful Response
   */
  200: ReloadRolesResponse;
};

export type AuthReloadRolesResponse = AuthReloadRolesResponses[keyof AuthReloadRolesResponses];

export type GetTokenStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/repos/staging/token-status";
};

export type GetTokenStatusResponses = {
  /**
   * Successful Response
   */
  200: TokenStatus;
};

export type GetTokenStatusResponse = GetTokenStatusResponses[keyof GetTokenStatusResponses];

export type ListReposData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/repos/staging/";
};

export type ListReposResponses = {
  /**
   * Response Listrepos
   *
   * Successful Response
   */
  200: Array<StagingMeta>;
};

export type ListReposResponse = ListReposResponses[keyof ListReposResponses];

export type GetAllReposTreeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/repos/staging/tree";
};

export type GetAllReposTreeResponses = {
  /**
   * Response Getallrepostree
   *
   * Successful Response
   */
  200: Array<StagingTreeInfo>;
};

export type GetAllReposTreeResponse = GetAllReposTreeResponses[keyof GetAllReposTreeResponses];

export type RegisterRepoData = {
  body: RepoCreateRequest;
  path?: never;
  query?: never;
  url: "/api/v1/repos/staging/register";
};

export type RegisterRepoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterRepoError = RegisterRepoErrors[keyof RegisterRepoErrors];

export type RegisterRepoResponses = {
  /**
   * Response Registerrepo
   *
   * Successful Response
   */
  200: Array<StagingTreeInfo>;
};

export type RegisterRepoResponse = RegisterRepoResponses[keyof RegisterRepoResponses];

export type UnregisterRepoData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/unregister";
};

export type UnregisterRepoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UnregisterRepoError = UnregisterRepoErrors[keyof UnregisterRepoErrors];

export type UnregisterRepoResponses = {
  /**
   * Response Unregisterrepo
   *
   * Successful Response
   */
  200: Array<StagingTreeInfo>;
};

export type UnregisterRepoResponse = UnregisterRepoResponses[keyof UnregisterRepoResponses];

export type ListRepoRefsData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/refs";
};

export type ListRepoRefsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListRepoRefsError = ListRepoRefsErrors[keyof ListRepoRefsErrors];

export type ListRepoRefsResponses = {
  /**
   * Response Listreporefs
   *
   * Successful Response
   */
  200: Array<RepoRef>;
};

export type ListRepoRefsResponse = ListRepoRefsResponses[keyof ListRepoRefsResponses];

export type SyncRepoData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/sync";
};

export type SyncRepoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SyncRepoError = SyncRepoErrors[keyof SyncRepoErrors];

export type SyncRepoResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type SyncRepoResponse = SyncRepoResponses[keyof SyncRepoResponses];

export type GetStagingRepoFileData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * Path to file inside repository
     */
    path: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/file";
};

export type GetStagingRepoFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetStagingRepoFileError = GetStagingRepoFileErrors[keyof GetStagingRepoFileErrors];

export type GetStagingRepoFileResponses = {
  /**
   * Successful Response
   */
  200: FileResponse;
};

export type GetStagingRepoFileResponse =
  GetStagingRepoFileResponses[keyof GetStagingRepoFileResponses];

export type UpdateStagingRepoFileData = {
  body: FileUpdateRequest;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * Path to existing file inside repository (relative to root)
     */
    path: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/file";
};

export type UpdateStagingRepoFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateStagingRepoFileError =
  UpdateStagingRepoFileErrors[keyof UpdateStagingRepoFileErrors];

export type UpdateStagingRepoFileResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type UpdateStagingRepoFileResponse =
  UpdateStagingRepoFileResponses[keyof UpdateStagingRepoFileResponses];

export type UploadStagingRepoFileData = {
  body: BodyUploadStagingRepoFile;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * Destination path for the file, relative to repo root (e.g. images/logo.png)
     */
    path: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/upload";
};

export type UploadStagingRepoFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UploadStagingRepoFileError =
  UploadStagingRepoFileErrors[keyof UploadStagingRepoFileErrors];

export type UploadStagingRepoFileResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type UploadStagingRepoFileResponse =
  UploadStagingRepoFileResponses[keyof UploadStagingRepoFileResponses];

export type ResetStagingRepoFileData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * Path to file inside repository (relative to root)
     */
    path: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/file/reset";
};

export type ResetStagingRepoFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetStagingRepoFileError =
  ResetStagingRepoFileErrors[keyof ResetStagingRepoFileErrors];

export type ResetStagingRepoFileResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type ResetStagingRepoFileResponse =
  ResetStagingRepoFileResponses[keyof ResetStagingRepoFileResponses];

export type ResetStagingRepoPathData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * File or directory path inside repository (relative to root)
     */
    path: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/path/reset";
};

export type ResetStagingRepoPathErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetStagingRepoPathError =
  ResetStagingRepoPathErrors[keyof ResetStagingRepoPathErrors];

export type ResetStagingRepoPathResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type ResetStagingRepoPathResponse =
  ResetStagingRepoPathResponses[keyof ResetStagingRepoPathResponses];

export type ResetStagingRepoData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/reset";
};

export type ResetStagingRepoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetStagingRepoError = ResetStagingRepoErrors[keyof ResetStagingRepoErrors];

export type ResetStagingRepoResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type ResetStagingRepoResponse = ResetStagingRepoResponses[keyof ResetStagingRepoResponses];

export type DeleteStagingRepoPathData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * FIle or directory path inside repository, relative to root.
     */
    path: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/path";
};

export type DeleteStagingRepoPathErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteStagingRepoPathError =
  DeleteStagingRepoPathErrors[keyof DeleteStagingRepoPathErrors];

export type DeleteStagingRepoPathResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type DeleteStagingRepoPathResponse =
  DeleteStagingRepoPathResponses[keyof DeleteStagingRepoPathResponses];

export type CreateStagingRepoPathData = {
  body: PathCreateRequest;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/path";
};

export type CreateStagingRepoPathErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateStagingRepoPathError =
  CreateStagingRepoPathErrors[keyof CreateStagingRepoPathErrors];

export type CreateStagingRepoPathResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type CreateStagingRepoPathResponse =
  CreateStagingRepoPathResponses[keyof CreateStagingRepoPathResponses];

export type RenameStagingRepoPathData = {
  body: PathRenameRequest;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * File or directory path inside repository, relative to root.
     */
    path: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/path/rename";
};

export type RenameStagingRepoPathErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RenameStagingRepoPathError =
  RenameStagingRepoPathErrors[keyof RenameStagingRepoPathErrors];

export type RenameStagingRepoPathResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type RenameStagingRepoPathResponse =
  RenameStagingRepoPathResponses[keyof RenameStagingRepoPathResponses];

export type MoveStagingRepoPathData = {
  body: PathMoveRequest;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * File or directory path to move, relative to repo root.
     */
    path: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/path/move";
};

export type MoveStagingRepoPathErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type MoveStagingRepoPathError = MoveStagingRepoPathErrors[keyof MoveStagingRepoPathErrors];

export type MoveStagingRepoPathResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type MoveStagingRepoPathResponse =
  MoveStagingRepoPathResponses[keyof MoveStagingRepoPathResponses];

export type CommitStagingRepoData = {
  body: CommitRequest;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/commit";
};

export type CommitStagingRepoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CommitStagingRepoError = CommitStagingRepoErrors[keyof CommitStagingRepoErrors];

export type CommitStagingRepoResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type CommitStagingRepoResponse =
  CommitStagingRepoResponses[keyof CommitStagingRepoResponses];

export type DeployRepoData = {
  body: DeployRequest;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/deploy";
};

export type DeployRepoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeployRepoError = DeployRepoErrors[keyof DeployRepoErrors];

export type DeployRepoResponses = {
  /**
   * Successful Response
   */
  200: StagingMeta;
};

export type DeployRepoResponse = DeployRepoResponses[keyof DeployRepoResponses];

export type UndeployRepoData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/undeploy";
};

export type UndeployRepoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UndeployRepoError = UndeployRepoErrors[keyof UndeployRepoErrors];

export type UndeployRepoResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CheckoutRepoRefData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Ref
     */
    ref: string;
  };
  url: "/api/v1/repos/staging/{repo_id}/checkout";
};

export type CheckoutRepoRefErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CheckoutRepoRefError = CheckoutRepoRefErrors[keyof CheckoutRepoRefErrors];

export type CheckoutRepoRefResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type CheckoutRepoRefResponse = CheckoutRepoRefResponses[keyof CheckoutRepoRefResponses];

export type GetStagingRepoTreeData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/staging/{repo_id}/tree";
};

export type GetStagingRepoTreeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetStagingRepoTreeError = GetStagingRepoTreeErrors[keyof GetStagingRepoTreeErrors];

export type GetStagingRepoTreeResponses = {
  /**
   * Successful Response
   */
  200: StagingTreeInfo;
};

export type GetStagingRepoTreeResponse =
  GetStagingRepoTreeResponses[keyof GetStagingRepoTreeResponses];

export type ListDeployedReposData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/repos/runtime/";
};

export type ListDeployedReposResponses = {
  /**
   * Response Listdeployedrepos
   *
   * Successful Response
   */
  200: Array<DeploymentMeta>;
};

export type ListDeployedReposResponse =
  ListDeployedReposResponses[keyof ListDeployedReposResponses];

export type GetAllDeployedReposTreeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/repos/runtime/tree";
};

export type GetAllDeployedReposTreeResponses = {
  /**
   * Response Getalldeployedrepostree
   *
   * Successful Response
   */
  200: Array<DeploymentTreeInfo>;
};

export type GetAllDeployedReposTreeResponse =
  GetAllDeployedReposTreeResponses[keyof GetAllDeployedReposTreeResponses];

export type GetDeployedRepoTreeData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query?: never;
  url: "/api/v1/repos/runtime/{repo_id}/tree";
};

export type GetDeployedRepoTreeErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetDeployedRepoTreeError = GetDeployedRepoTreeErrors[keyof GetDeployedRepoTreeErrors];

export type GetDeployedRepoTreeResponses = {
  /**
   * Successful Response
   */
  200: DeploymentTreeInfo;
};

export type GetDeployedRepoTreeResponse =
  GetDeployedRepoTreeResponses[keyof GetDeployedRepoTreeResponses];

export type GetDeployedRepoFileData = {
  body?: never;
  path: {
    /**
     * Repo Id
     */
    repo_id: string;
  };
  query: {
    /**
     * Path
     *
     * Path to file inside repository
     */
    path: string;
  };
  url: "/api/v1/repos/runtime/{repo_id}/file";
};

export type GetDeployedRepoFileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetDeployedRepoFileError = GetDeployedRepoFileErrors[keyof GetDeployedRepoFileErrors];

export type GetDeployedRepoFileResponses = {
  /**
   * Successful Response
   */
  200: FileResponse;
};

export type GetDeployedRepoFileResponse =
  GetDeployedRepoFileResponses[keyof GetDeployedRepoFileResponses];

export type ListSnapshotsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Opi File
     *
     * OPI file path
     */
    opi_file: string;
  };
  url: "/api/v1/snapshots";
};

export type ListSnapshotsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSnapshotsError = ListSnapshotsErrors[keyof ListSnapshotsErrors];

export type ListSnapshotsResponses = {
  /**
   * Response Listsnapshots
   *
   * Successful Response
   */
  200: Array<SnapshotEntry>;
};

export type ListSnapshotsResponse = ListSnapshotsResponses[keyof ListSnapshotsResponses];

export type SaveSnapshotData = {
  body: SnapshotSaveRequest;
  path?: never;
  query?: never;
  url: "/api/v1/snapshots";
};

export type SaveSnapshotErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SaveSnapshotError = SaveSnapshotErrors[keyof SaveSnapshotErrors];

export type SaveSnapshotResponses = {
  /**
   * Successful Response
   */
  200: SnapshotEntry;
};

export type SaveSnapshotResponse = SaveSnapshotResponses[keyof SaveSnapshotResponses];

export type DeleteSnapshotData = {
  body?: never;
  path: {
    /**
     * Snapshot Id
     */
    snapshot_id: string;
  };
  query: {
    /**
     * Opi File
     *
     * OPI file path
     */
    opi_file: string;
  };
  url: "/api/v1/snapshots/{snapshot_id}";
};

export type DeleteSnapshotErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteSnapshotError = DeleteSnapshotErrors[keyof DeleteSnapshotErrors];

export type DeleteSnapshotResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetSnapshotData = {
  body?: never;
  path: {
    /**
     * Snapshot Id
     */
    snapshot_id: string;
  };
  query: {
    /**
     * Opi File
     *
     * OPI file path
     */
    opi_file: string;
  };
  url: "/api/v1/snapshots/{snapshot_id}";
};

export type GetSnapshotErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSnapshotError = GetSnapshotErrors[keyof GetSnapshotErrors];

export type GetSnapshotResponses = {
  /**
   * Successful Response
   */
  200: SnapshotDetail;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];

export type RootInfoData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type RootInfoResponses = {
  /**
   * Successful Response
   */
  200: RootInfo;
};

export type RootInfoResponse = RootInfoResponses[keyof RootInfoResponses];

export type HealthCheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckResponses = {
  /**
   * Successful Response
   */
  200: Health;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
