services:
  weiss-docs:
    build:
      context: .
    image: weiss-docs:latest
    container_name: weiss-docs
    restart: always
    networks:
      - weiss-public

networks:
  weiss-public:
    external: true
    name: weiss-public
